feat: 暴露解析 excel 文件函数(parseExcel)
FEMessage/excel-it pull request #26
Opened 2019-10-16 06:44 UTC by eviIIt

close #25 

## Why

- 场景需求, 提供解析 excel  文件函数

## How

- 暴露 `parseExcel` 函数
- 复用 `importExcel` 内 `parseExcel` 代码

## Usage

### 参数

#### file

excel 文件

#### ignore

要忽略的表头单元格范围

#### data

excel 第一行外其他行的数据

```js
import { parseExcel } from '@femessage/excel-it'

parseExcel(file, ignore, data => {
  // data
})
```

## Showcase

![parse-excel](https://user-images.githubusercontent.com/53422750/66893634-1b0dff80-f021-11e9-81b9-fc59aa98e60e.gif)

## Test

测试导入功能是否正常可用

![parse-excel1](https://user-images.githubusercontent.com/53422750/66893683-337e1a00-f021-11e9-877e-c0e5c3da0cf2.gif)

## Docs

- 新增 parse-excel 示例

2019-10-16 06:57 UTC, colmugx commented on docs/api.md
> +| -------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
怎么这么长..

2019-10-16 06:58 UTC, eviIIt commented on docs/api.md
> +| -------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
prettier 自动格式化

2019-10-16 07:01 UTC, colmugx commented on docs/parse-excel.md
> +// import { parseExcel } from '@femessage/excel-it'
```suggestion
import { parseExcel } from '@femessage/excel-it'
```

2019-10-16 07:09 UTC, donaldshen approved these changes

2019-10-16 07:11 UTC, colmugx approved these changes

2019-10-16 07:51 UTC, levy9527 requested changes

2019-10-16 07:51 UTC, levy9527 commented on src/index.js
> +      const file = e.target.files[0]
把函数逻辑放前面，函数定义放后面

2019-10-16 08:30 UTC, donaldshen approved these changes

2019-10-16 08:33 UTC, levy9527 approved these changes

2019-10-16 08:33 UTC, merged

2019-10-29 08:04 UTC, levy9527 commented
@all-contributors add @eviIIt code,doc

2019-10-29 08:05 UTC, levy9527 commented
@all-contributors add @eviIIt code and doc